global:
  scrape_interval: 15s
  scrape_timeout: 15s
scrape_configs:
  - job_name: 'nobreaks'
    static_configs:
      - targets:
        - 127.0.0.1  # Dispositivo SNMP.
    metrics_path: /snmp
    params:
      auth: [public_v1]
      module: [teste]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116  # O <real IP>:<Porta> do SNMP exporter.
